# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - name: Install SwaggerHub CLI
      run: |
        npm install swaggerhub-cli -g
    - name: Publish the API definition
      env:
        SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
      run: |
        swaggerhub api:publish SE-Design/CN-Demo-API/1.0.0
